//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSC
    {
        public int Id { get; set; }
        public string Qualification { get; set; }
        public string University { get; set; }
        public string Percentage { get; set; }
        public string YearOfPassing { get; set; }
    }
}
