//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string DOB { get; set; }
        public string PermanentAddress { get; set; }
        public string LanguagesKnown { get; set; }
        public string Hobbies { get; set; }
        public string DECLARATION { get; set; }
    }
}
