//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Resume290820Entities1 : DbContext
    {
        public Resume290820Entities1()
            : base("name=Resume290820Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Graduation> Graduations { get; set; }
        public virtual DbSet<HSC> HSCs { get; set; }
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<SSC> SSCs { get; set; }
        public virtual DbSet<TechnicalSkill> TechnicalSkills { get; set; }
    }
}
