//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalSkill
    {
        public int Id { get; set; }
        public string Certification { get; set; }
        public string ProgrammingLanguage { get; set; }
        public string DataBaseUsed { get; set; }
        public string FrameworkUsed { get; set; }
        public string OperatingSystem { get; set; }
    }
}
